[package]
name = "mat_model"
version = "0.1.0"
edition = "2024"

[dependencies]
candle-core = "0.6.0"  # Adjust to the latest version of candle-core
ndarray = "0.16.1"     # For working with multi-dimensional arrays in Rust
