[package]
name = "mat_model"
version = "0.1.0"
edition = "2021"

[dependencies]
candle-core = "0.1.0"  # Adjust to the latest version of candle-core
ndarray = "0.15"       # For working with multi-dimensional arrays in Rust
